package tn.dossier.demo.entity;

// Generated 6 ao�t 2013 15:04:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Cahiercharges generated by hbm2java
 */
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer"})
@Table(name = "cahiercharges")
public class CahierCharges implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6630840835358775645L;
	private Long cahierChargesId;
	private Categoriesprojet categoriesprojet;
	private String cahierChargesLibelle;
	private String cahierChargesDescription;
	private Set<Cahierclausesfinancierestechniques> cahierclausesfinancierestechniques = new HashSet<Cahierclausesfinancierestechniques>(
			0);
	private Set<Cahierclausesadministratives> cahierclausesadministratives = new HashSet<Cahierclausesadministratives>(0);

	public CahierCharges() {
	}

	public CahierCharges(
			Categoriesprojet categoriesprojet,
			String cahierChargesLibelle,
			String cahierChargesDescription, Set<Cahierclausesadministratives> cahierclausesadministratives,
			Set<Cahierclausesfinancierestechniques> cahierclausesfinancierestechniques) {
		this.categoriesprojet = categoriesprojet;
		this.cahierChargesLibelle = cahierChargesLibelle;
		this.cahierChargesDescription = cahierChargesDescription;
	this.cahierclausesfinancierestechniques = cahierclausesfinancierestechniques;
		this.cahierclausesadministratives = cahierclausesadministratives;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cahierChargesId", unique = true, nullable = false)
	public Long getCahierChargesId() {
		return this.cahierChargesId;
	}

	public void setCahierChargesId(Long cahierChargesId) {
		this.cahierChargesId = cahierChargesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoriesProjetId")
	public Categoriesprojet getCategoriesprojet() {
		return this.categoriesprojet;
	}

	public void setCategoriesprojet(Categoriesprojet categoriesprojet) {
		this.categoriesprojet = categoriesprojet;
	}

	@Column(name = "cahierChargesLibelle", length = 100)
	public String getCahierChargesLibelle() {
		return this.cahierChargesLibelle;
	}

	public void setCahierChargesLibelle(String cahierChargesLibelle) {
		this.cahierChargesLibelle = cahierChargesLibelle;
	}

	@Column(name = "cahierChargesDescription", length = 65535)
	public String getCahierChargesDescription() {
		return this.cahierChargesDescription;
	}

	public void setCahierChargesDescription(String cahierChargesDescription) {
		this.cahierChargesDescription = cahierChargesDescription;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cahiercharges")
	public Set<Cahierclausesfinancierestechniques> getCahierclausesfinancierestechniques() {
		return this.cahierclausesfinancierestechniques;
	}

	public void setCahierclausesfinancierestechniques(
			Set<Cahierclausesfinancierestechniques> cahierclausesfinancierestechniques) {
		this.cahierclausesfinancierestechniques = cahierclausesfinancierestechniques;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cahiercharges")
	public Set<Cahierclausesadministratives> getCahierclausesadministratives() {
		return cahierclausesadministratives;
	}

	public void setCahierclausesadministratives(Set<Cahierclausesadministratives> cahierclausesadministratives) {
		this.cahierclausesadministratives = cahierclausesadministratives;
	}

*/

	public CahierCharges(Long cahierChargesId, Categoriesprojet categoriesprojet, String cahierChargesLibelle,
			String cahierChargesDescription) {
		super();
		this.cahierChargesId = cahierChargesId;
		this.categoriesprojet = categoriesprojet;
		this.cahierChargesLibelle = cahierChargesLibelle;
		this.cahierChargesDescription = cahierChargesDescription;
		
	}

	@Override
	public String toString() {
		return "CahierCharges [cahierChargesId=" + cahierChargesId + ", categoriesprojet=" + categoriesprojet
				+ ", cahierChargesLibelle=" + cahierChargesLibelle + ", cahierChargesDescription="
				+ cahierChargesDescription + ", cahierclausesfinancierestechniques="
				+ cahierclausesfinancierestechniques + ", cahierclausesadministratives=" + cahierclausesadministratives
				+ "]";
	}


	
	
}
